// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn4qFmi1zpDh32Quvpkv9DoY_l9CRtYXk',
    appId: '1:716300943335:web:97bc048cda0efda4660742',
    messagingSenderId: '716300943335',
    projectId: 'flash-chat-honey',
    authDomain: 'flash-chat-honey.firebaseapp.com',
    storageBucket: 'flash-chat-honey.appspot.com',
    measurementId: 'G-NKJY13GJZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8AdN8HioMn2V4v90OxZdoebgTCUnwHZM',
    appId: '1:716300943335:android:cceba2dda84f908e660742',
    messagingSenderId: '716300943335',
    projectId: 'flash-chat-honey',
    storageBucket: 'flash-chat-honey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUrpgXfuAXcEWu653DaZyHMnBYiCB95Yw',
    appId: '1:716300943335:ios:569cb3b40deda12f660742',
    messagingSenderId: '716300943335',
    projectId: 'flash-chat-honey',
    storageBucket: 'flash-chat-honey.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
